mysql_41:
  host: sg.evercomm.com
  port: 44106
  user: eco
  password: ECO4ever

mysql_42:
  host: sg.evercomm.com
  port: 44206
  user: eco
  password: ECO4ever

mysql_own:
  host: 192.168.0.109
  port: 3306
  user: admin
  password: Aaron8118!